language: node_js
node_js:
  - '4'
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - mesa-utils
    - xvfb
    - libgl1-mesa-dri
    - libglapi-mesa
    - libosmesa6
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export LIBGL_ALWAYS_SOFTWARE=1
script:
  - echo 'deployPending' && echo -en 'travis_fold:start:script.deployPending\\r'
  - npm run deploy-set-version -- --version $TRAVIS_BRANCH.$TRAVIS_BUILD_NUMBER
  - npm run deploy-status -- --status pending --message 'Waiting for build'
  - echo -en 'travis_fold:end:script.deployPending\\r'

  - echo 'test' && echo -en 'travis_fold:start:script.test\\r'
  - npm run build
  - npm run test -- --browsers Chrome --failTaskOnError --suppressPassed
  - echo -en 'travis_fold:end:script.test\\r'

  - echo 'deploy' && echo -en 'travis_fold:start:script.deploy\\r'
  - npm run deploy-s3 -- -b cesium-dev -d cesium/$TRAVIS_BRANCH --confirm -c 'no-cache'
  - npm run deploy-status -- --status success --message Deployed
  - echo -en 'travis_fold:end:script.deploy\\r'
